# Generated by Django 5.0.7 on 2024-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
