# Generated by Django 5.0.7 on 2024-08-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0002_alter_instructor_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='time_table_api.customuser'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='time_table_api.customuser'),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
