# Generated by Django 5.0.7 on 2024-08-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0003_conflict_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
