# Generated by Django 5.0.7 on 2024-08-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0006_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
