# Generated by Django 5.0.7 on 2024-08-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0007_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
