# Generated by Django 5.0.7 on 2024-08-18 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table_api', '0010_batch_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL),
        ),
    ]
